

TEMP_ENV_VARS = {
          'AWS_DEFAULT_REGION' : 'us-east-1',
          'TEST_ID': 'kkm-c19ag',
          'DETECTION_ENDPOINT_NAME': 'kkm-c19ag-maskrcnn-cpu-v3-0-dkr-v3',
          'CLASSIFICATION_ENDPOINT_NAME': 'kkm-c19ag-classifier-v3-3-dkr-v3',
          'KIT_DATA_JSON_PATH': 'kkm-c19ag-data-v1.json',
          'SAVE_IMAGES': 'True',
          'TRY_180_FLIP': 'False',
          'PROCESS_CODE_IF_DETECTED': 'False',
          'REQUIRE_DETECT_CODE': 'False',
          'APPLY_AMBIGUITY_ZONE_1': 'False',
          'APPLY_AMBIGUITY_ZONE_2': 'False',
          'MAX_HEIGHT': '800',
          'MAX_WIDTH': '-1',
          'CODE_BUFFER': '0.0',
          'CODE_BORDER': '0.0',
          'CODE_BLUR': '0',
          'KIT_BOX_THRESHOLD': '0.75',
          'MEMBRANE_BOX_THRESHOLD': '0.85',
          'CODE_BOX_THRESHOLD': '0.85',
          'KIT_MASK_THRESHOLD': '0.60',
          'MEMBRANE_MASK_THRESHOLD': '0.85',
          'CODE_MASK_THRESHOLD': '0.85',
          'ANGLE_CALCULATION_METHOD': 'kit_mask',
          'ANGLE_THRESHOLD': '20',
          'MEMBRANE_LOCALIZATION_THRESHOLD': '0.0',
          'CODE_LOCALIZATION_THRESHOLD': '0.0',
          'AMBIGUITY_ZONE_LOWER_1': '0.50',
          'AMBIGUITY_ZONE_UPPER_1': '0.50',
          'AMBIGUITY_ZONE_LOWER_2': '0.50',
          'AMBIGUITY_ZONE_UPPER_2': '0.50',
   
}